### ISSUE TITLE
Send alert name in Graphite request header

### ISSUE THREAD

**Issue by grzkv** [bosun-monitor/bosun#2251]
Bosun can add [custom headers in Graphite requests](https://bosun.org/system_configuration#graphiteconfheaders). However, these are static.

We need to send alert names as header values. This would improve diagnostics. This will also add the ability to track load alerts put on Graphite.

The main question is the syntax in the config file. The simplest way to proceed is to add some sort of "magic string" as the header value. When encountered, it will be converted to alert name. For example:
```toml
[GraphiteConf]
	Host = "localhost:80"
	[GraphiteConf.Headers]
		Static-Header = "Content"
		Alert-Name-Header = "{alert-name}"
```
`{alert-name}` will be expanded to something like `cpu.is.too.high` in the request header.

Please, share your thoughts.
